<?php

class PeThemeConstantData {
	public $yesno;
	public $delay;
	public $icons;
	public $fields;
	public $faicons;
	public $elicons;
	public $outlinediconset;
	public $ionicons;

	public function __construct() {
		$this->yesno = 
			array(
				  __("Yes",'Pixelentity Theme/Plugin')=>"yes",
				  __("No",'Pixelentity Theme/Plugin')=>"no"
				  );
		
		$this->delay = 
			array(
				  __("Don't Auto Rotate Slides",'Pixelentity Theme/Plugin')=>0,
				  "2" => 2,
				  "3" => 3,
				  "4" => 4,
				  "5" => 5,
				  "6" => 6,
				  "7" => 7,
				  "8" => 8,
				  "9" => 9,
				  "10" => 10,
				  "15" => 15,
				  "20" => 20,
				  "25" => 25,
				  "30" => 30
				  );

		$this->icons = 
			array(
				  "icon-address",
				  "icon-adjust",
				  "icon-aim",
				  "icon-air",
				  "icon-alert",
				  "icon-amazon",
				  "icon-android",
				  "icon-appstore",
				  "icon-archive",
				  "icon-arrow-combo",
				  "icon-arrows-ccw",
				  "icon-attach",
				  "icon-attention",
				  "icon-back",
				  "icon-back-in-time",
				  "icon-bag",
				  "icon-basket",
				  "icon-battery",
				  "icon-behance",
				  "icon-bell",
				  "icon-block",
				  "icon-blogger",
				  "icon-book",
				  "icon-bookmark",
				  "icon-bookmarks",
				  "icon-book-open",
				  "icon-box",
				  "icon-briefcase",
				  "icon-brush",
				  "icon-bucket",
				  "icon-calendar",
				  "icon-camera",
				  "icon-cancel",
				  "icon-cancel-circled",
				  "icon-cancel-squared",
				  "icon-cc",
				  "icon-cc-1",
				  "icon-cc-by",
				  "icon-cc-nc",
				  "icon-cc-nc-eu",
				  "icon-cc-nc-jp",
				  "icon-cc-nd",
				  "icon-cc-pd",
				  "icon-cc-remix",
				  "icon-cc-sa",
				  "icon-cc-share",
				  "icon-ccw",
				  "icon-cc-zero",
				  "icon-cd",
				  "icon-chart-area",
				  "icon-chart-bar",
				  "icon-chart-line",
				  "icon-chart-pie",
				  "icon-chat",
				  "icon-check",
				  "icon-clipboard",
				  "icon-clock",
				  "icon-cloud",
				  "icon-cloud-thunder",
				  "icon-code",
				  "icon-cog",
				  "icon-comment",
				  "icon-compass",
				  "icon-credit-card",
				  "icon-cup",
				  "icon-cw",
				  "icon-database",
				  "icon-db-shape",
				  "icon-delicious",
				  "icon-digg",
				  "icon-direction",
				  "icon-doc",
				  "icon-doc-landscape",
				  "icon-docs",
				  "icon-doc-text",
				  "icon-doc-text-inv",
				  "icon-dot",
				  "icon-dot-2",
				  "icon-dot-3",
				  "icon-down",
				  "icon-down-bold",
				  "icon-down-circled",
				  "icon-down-dir",
				  "icon-download",
				  "icon-down-open",
				  "icon-down-open-big",
				  "icon-down-open-mini",
				  "icon-down-thin",
				  "icon-dribbble",
				  "icon-dribbble-circled",
				  "icon-drive",
				  "icon-dropbox",
				  "icon-dropbox-1",
				  "icon-droplet",
				  "icon-drupal",
				  "icon-ebay",
				  "icon-erase",
				  "icon-evernote",
				  "icon-evernote-1",
				  "icon-export",
				  "icon-eye",
				  "icon-facebook",
				  "icon-facebook-circled",
				  "icon-facebook-squared",
				  "icon-fast-backward",
				  "icon-fast-forward",
				  "icon-feather",
				  "icon-flag",
				  "icon-flash",
				  "icon-flashlight",
				  "icon-flattr",
				  "icon-flickr",
				  "icon-flickr-circled",
				  "icon-flight",
				  "icon-floppy",
				  "icon-flow-branch",
				  "icon-flow-cascade",
				  "icon-flow-line",
				  "icon-flow-parallel",
				  "icon-flow-tree",
				  "icon-folder",
				  "icon-forrst",
				  "icon-forward",
				  "icon-gauge",
				  "icon-github",
				  "icon-github-1",
				  "icon-github-circled",
				  "icon-globe",
				  "icon-gmail",
				  "icon-google-circles",
				  "icon-gowalla",
				  "icon-gplus",
				  "icon-gplus-circled",
				  "icon-graduation-cap",
				  "icon-grooveshark",
				  "icon-heart",
				  "icon-heart-empty",
				  "icon-help",
				  "icon-help-circled",
				  "icon-home",
				  "icon-hourglass",
				  "icon-html5",
				  "icon-ie",
				  "icon-inbox",
				  "icon-infinity",
				  "icon-info",
				  "icon-info-circled",
				  "icon-instagram",
				  "icon-install",
				  "icon-itunes",
				  "icon-key",
				  "icon-keyboard",
				  "icon-lamp",
				  "icon-language",
				  "icon-lastfm",
				  "icon-lastfm-1",
				  "icon-lastfm-circled",
				  "icon-layout",
				  "icon-leaf",
				  "icon-left",
				  "icon-left-bold",
				  "icon-left-circled",
				  "icon-left-dir",
				  "icon-left-open",
				  "icon-left-open-big",
				  "icon-left-open-mini",
				  "icon-left-thin",
				  "icon-level-down",
				  "icon-level-up",
				  "icon-lifebuoy",
				  "icon-light-down",
				  "icon-light-up",
				  "icon-link",
				  "icon-linkedin",
				  "icon-linkedin-circled",
				  "icon-list",
				  "icon-list-add",
				  "icon-location",
				  "icon-lock",
				  "icon-lock-open",
				  "icon-login",
				  "icon-logo-db",
				  "icon-logout",
				  "icon-loop",
				  "icon-macstore",
				  "icon-magnet",
				  "icon-mail",
				  "icon-map",
				  "icon-megaphone",
				  "icon-menu",
				  "icon-mic",
				  "icon-minus",
				  "icon-minus-circled",
				  "icon-minus-squared",
				  "icon-mixi",
				  "icon-mobile",
				  "icon-monitor",
				  "icon-moon",
				  "icon-mouse",
				  "icon-music",
				  "icon-mute",
				  "icon-network",
				  "icon-newspaper",
				  "icon-note",
				  "icon-note-beamed",
				  "icon-palette",
				  "icon-paper-plane",
				  "icon-pause",
				  "icon-paypal",
				  "icon-paypal-1",
				  "icon-pencil",
				  "icon-phone",
				  "icon-picasa",
				  "icon-picture",
				  "icon-pinterest",
				  "icon-pinterest-circled",
				  "icon-play",
				  "icon-plus",
				  "icon-plus-circled",
				  "icon-plus-squared",
				  "icon-popup",
				  "icon-print",
				  "icon-progress-0",
				  "icon-progress-1",
				  "icon-progress-2",
				  "icon-progress-3",
				  "icon-publish",
				  "icon-qq",
				  "icon-quote",
				  "icon-rdio",
				  "icon-rdio-circled",
				  "icon-record",
				  "icon-reddit",
				  "icon-renren",
				  "icon-reply",
				  "icon-reply-all",
				  "icon-resize-full",
				  "icon-resize-small",
				  "icon-retweet",
				  "icon-right",
				  "icon-right-bold",
				  "icon-right-circled",
				  "icon-right-dir",
				  "icon-right-open",
				  "icon-right-open-big",
				  "icon-right-open-mini",
				  "icon-right-thin",
				  "icon-rocket",
				  "icon-rss",
				  "icon-search",
				  "icon-share",
				  "icon-shareable",
				  "icon-shuffle",
				  "icon-signal",
				  "icon-sina-weibo",
				  "icon-skype",
				  "icon-skype-circled",
				  "icon-smashing",
				  "icon-smashmag",
				  "icon-sound",
				  "icon-soundcloud",
				  "icon-soundcloud-1",
				  "icon-spotify",
				  "icon-spotify-circled",
				  "icon-star",
				  "icon-star-empty",
				  "icon-stop",
				  "icon-stumbleupon",
				  "icon-stumbleupon-circled",
				  "icon-suitcase",
				  "icon-sweden",
				  "icon-switch",
				  "icon-tag",
				  "icon-tape",
				  "icon-target",
				  "icon-thermometer",
				  "icon-thumbs-down",
				  "icon-thumbs-up",
				  "icon-ticket",
				  "icon-to-end",
				  "icon-tools",
				  "icon-to-start",
				  "icon-traffic-cone",
				  "icon-trash",
				  "icon-trophy",
				  "icon-tumblr",
				  "icon-tumblr-circled",
				  "icon-twitter",
				  "icon-twitter-circled",
				  "icon-up",
				  "icon-up-bold",
				  "icon-up-circled",
				  "icon-up-dir",
				  "icon-upload",
				  "icon-upload-cloud",
				  "icon-up-open",
				  "icon-up-open-big",
				  "icon-up-open-mini",
				  "icon-up-thin",
				  "icon-user",
				  "icon-user-add",
				  "icon-users",
				  "icon-vcard",
				  "icon-video",
				  "icon-vimeo",
				  "icon-vimeo-circled",
				  "icon-vkontakte",
				  "icon-volume",
				  "icon-w3c",
				  "icon-water",
				  "icon-window",
				  "icon-windows",
				  "icon-wordpress",
				  "icon-yahoo",
				  "icon-youtube"
				  );
			

		$this->fields = new StdClass();

		$this->fields->icon =
			array(
				  "label" => __("Icon Type",'Pixelentity Theme/Plugin'),
				  "type" => "Select",
				  "description" => __("Select the desired icon type. See the help documentation for a link to view the available icons",'Pixelentity Theme/Plugin'),
				  "single" => true,
				  "options" => $this->outlinediconset,
				  "default" => "icon icon-boat"
				  );

		$this->faicons = array(
			'fa fa-adjust',
			'fa fa-adn',
			'fa fa-align-center',
			'fa fa-align-justify',
			'fa fa-align-left',
			'fa fa-align-right',
			'fa fa-ambulance',
			'fa fa-anchor',
			'fa fa-android',
			'fa fa-angle-double-down',
			'fa fa-angle-double-left',
			'fa fa-angle-double-right',
			'fa fa-angle-double-up',
			'fa fa-angle-down',
			'fa fa-angle-left',
			'fa fa-angle-right',
			'fa fa-angle-up',
			'fa fa-apple',
			'fa fa-archive',
			'fa fa-arrow-circle-down',
			'fa fa-arrow-circle-left',
			'fa fa-arrow-circle-o-down',
			'fa fa-arrow-circle-o-left',
			'fa fa-arrow-circle-o-right',
			'fa fa-arrow-circle-o-up',
			'fa fa-arrow-circle-right',
			'fa fa-arrow-circle-up',
			'fa fa-arrow-down',
			'fa fa-arrow-left',
			'fa fa-arrow-right',
			'fa fa-arrow-up',
			'fa fa-arrows',
			'fa fa-arrows-alt',
			'fa fa-arrows-h',
			'fa fa-arrows-v',
			'fa fa-asterisk',
			'fa fa-automobile',
			'fa fa-backward',
			'fa fa-bank',
			'fa fa-bar-chart-o',
			'fa fa-barcode',
			'fa fa-bars fa-lg',
			'fa fa-beer',
			'fa fa-behance',
			'fa fa-behance-square',
			'fa fa-bell',
			'fa fa-bell-o',
			'fa fa-bitbucket',
			'fa fa-bitbucket-square',
			'fa fa-bitcoin',
			'fa fa-bold',
			'fa fa-bolt',
			'fa fa-bomb',
			'fa fa-book',
			'fa fa-bookmark',
			'fa fa-bookmark-o',
			'fa fa-briefcase',
			'fa fa-btc',
			'fa fa-bug',
			'fa fa-building',
			'fa fa-building-o',
			'fa fa-bullhorn',
			'fa fa-bullseye',
			'fa fa-cab',
			'fa fa-calendar',
			'fa fa-calendar-o',
			'fa fa-camera-retro fa-fw',
			'fa fa-caret-down',
			'fa fa-caret-left',
			'fa fa-caret-right',
			'fa fa-caret-square-o-down',
			'fa fa-caret-square-o-left',
			'fa fa-caret-square-o-right',
			'fa fa-caret-square-o-up',
			'fa fa-caret-up',
			'fa fa-certificate',
			'fa fa-chain',
			'fa fa-chain-broken',
			'fa fa-check-circle',
			'fa fa-check-circle-o',
			'fa fa-check-square fa-fw',
			'fa fa-check-square-o',
			'fa fa-chevron-circle-down',
			'fa fa-chevron-circle-left',
			'fa fa-chevron-circle-right',
			'fa fa-chevron-circle-up',
			'fa fa-chevron-down',
			'fa fa-chevron-left',
			'fa fa-chevron-right',
			'fa fa-chevron-up',
			'fa fa-child',
			'fa fa-circle-o-notch',
			'fa fa-circle-thin',
			'fa fa-clipboard',
			'fa fa-clock-o',
			'fa fa-cloud',
			'fa fa-cloud-download',
			'fa fa-cloud-upload',
			'fa fa-cny',
			'fa fa-code-fork',
			'fa fa-codepen',
			'fa fa-coffee',
			'fa fa-cog',
			'fa fa-cogs',
			'fa fa-columns',
			'fa fa-comment',
			'fa fa-comment-o',
			'fa fa-comments',
			'fa fa-comments-o',
			'fa fa-compass',
			'fa fa-compress',
			'fa fa-copy',
			'fa fa-credit-card',
			'fa fa-crop',
			'fa fa-crosshairs',
			'fa fa-css3',
			'fa fa-cube fa-fw',
			'fa fa-cubes',
			'fa fa-cutlery',
			'fa fa-dashboard',
			'fa fa-database',
			'fa fa-dedent',
			'fa fa-delicious',
			'fa fa-desktop',
			'fa fa-deviantart',
			'fa fa-digg',
			'fa fa-dollar',
			'fa fa-dot-circle-o',
			'fa fa-download',
			'fa fa-dribbble',
			'fa fa-dropbox',
			'fa fa-drupal',
			'fa fa-edit',
			'fa fa-eject',
			'fa fa-ellipsis-h',
			'fa fa-ellipsis-v',
			'fa fa-empire',
			'fa fa-envelope-o',
			'fa fa-envelope-square',
			'fa fa-eraser',
			'fa fa-eur',
			'fa fa-euro',
			'fa fa-exchange',
			'fa fa-exclamation',
			'fa fa-exclamation-circle',
			'fa fa-exclamation-triangle',
			'fa fa-expand',
			'fa fa-external-link-square',
			'fa fa-eye',
			'fa fa-eye-slash',
			'fa fa-facebook',
			'fa fa-facebook-square',
			'fa fa-fast-backward',
			'fa fa-fast-forward',
			'fa fa-fax',
			'fa fa-female',
			'fa fa-fighter-jet',
			'fa fa-file-archive-o',
			'fa fa-file-audio-o',
			'fa fa-file-code-o',
			'fa fa-file-excel-o',
			'fa fa-file-image-o fa-fw',
			'fa fa-file-movie-o',
			'fa fa-file-o',
			'fa fa-file-pdf-o',
			'fa fa-file-photo-o',
			'fa fa-file-picture-o',
			'fa fa-file-powerpoint-o',
			'fa fa-file-sound-o',
			'fa fa-file-text-o fa-fw',
			'fa fa-file-video-o',
			'fa fa-file-word-o',
			'fa fa-file-zip-o',
			'fa fa-files-o',
			'fa fa-film',
			'fa fa-filter',
			'fa fa-fire',
			'fa fa-fire-extinguisher',
			'fa fa-flag fa-fw',
			'fa fa-flag',
			'fa fa-flag-checkered',
			'fa fa-flag-o',
			'fa fa-flash',
			'fa fa-flask',
			'fa fa-flickr',
			'fa fa-floppy-o',
			'fa fa-folder',
			'fa fa-folder-o',
			'fa fa-folder-open',
			'fa fa-folder-open-o',
			'fa fa-font',
			'fa fa-forward',
			'fa fa-foursquare',
			'fa fa-frown-o',
			'fa fa-gamepad',
			'fa fa-gavel',
			'fa fa-gbp',
			'fa fa-ge',
			'fa fa-gear',
			'fa fa-gears',
			'fa fa-gift',
			'fa fa-git-square',
			'fa fa-github fa-fw',
			'fa fa-github-alt',
			'fa fa-github-square',
			'fa fa-gittip',
			'fa fa-glass',
			'fa fa-globe',
			'fa fa-google',
			'fa fa-google-plus',
			'fa fa-google-plus-square',
			'fa fa-graduation-cap',
			'fa fa-group',
			'fa fa-h-square',
			'fa fa-hacker-news',
			'fa fa-hand-o-down',
			'fa fa-hand-o-left',
			'fa fa-hand-o-right fa-fw',
			'fa fa-hand-o-up',
			'fa fa-hdd-o',
			'fa fa-header',
			'fa fa-headphones',
			'fa fa-heart',
			'fa fa-heart-o',
			'fa fa-history',
			'fa fa-home',
			'fa fa-hospital-o',
			'fa fa-html5',
			'fa fa-image',
			'fa fa-inbox',
			'fa fa-indent',
			'fa fa-info',
			'fa fa-info-circle',
			'fa fa-inr',
			'fa fa-instagram',
			'fa fa-institution',
			'fa fa-italic',
			'fa fa-joomla',
			'fa fa-jpy',
			'fa fa-jsfiddle',
			'fa fa-key',
			'fa fa-keyboard-o',
			'fa fa-krw',
			'fa fa-language',
			'fa fa-laptop',
			'fa fa-leaf',
			'fa fa-legal',
			'fa fa-lemon-o',
			'fa fa-level-down',
			'fa fa-level-up',
			'fa fa-life-bouy',
			'fa fa-life-ring',
			'fa fa-life-saver',
			'fa fa-lightbulb-o',
			'fa fa-link',
			'fa fa-linkedin',
			'fa fa-linkedin-square',
			'fa fa-linux',
			'fa fa-list',
			'fa fa-list-alt',
			'fa fa-list-ol',
			'fa fa-list-ul',
			'fa fa-location-arrow',
			'fa fa-lock',
			'fa fa-long-arrow-down',
			'fa fa-long-arrow-left',
			'fa fa-long-arrow-right',
			'fa fa-long-arrow-up',
			'fa fa-magic',
			'fa fa-magnet',
			'fa fa-mail-forward',
			'fa fa-mail-reply',
			'fa fa-mail-reply-all',
			'fa fa-male',
			'fa fa-map-marker',
			'fa fa-maxcdn',
			'fa fa-medkit fa-fw',
			'fa fa-meh-o',
			'fa fa-microphone',
			'fa fa-microphone-slash',
			'fa fa-minus',
			'fa fa-minus-circle',
			'fa fa-minus-square',
			'fa fa-minus-square-o',
			'fa fa-mobile',
			'fa fa-mobile-phone',
			'fa fa-money',
			'fa fa-moon-o',
			'fa fa-mortar-board',
			'fa fa-music',
			'fa fa-navicon',
			'fa fa-openid',
			'fa fa-outdent',
			'fa fa-pagelines',
			'fa fa-paper-plane',
			'fa fa-paper-plane-o',
			'fa fa-paperclip',
			'fa fa-paragraph',
			'fa fa-paste',
			'fa fa-pause',
			'fa fa-paw',
			'fa fa-pencil',
			'fa fa-pencil-square',
			'fa fa-pencil-square-o',
			'fa fa-phone',
			'fa fa-phone-square',
			'fa fa-photo',
			'fa fa-picture-o',
			'fa fa-pied-piper',
			'fa fa-pied-piper-alt',
			'fa fa-pied-piper-square',
			'fa fa-pinterest',
			'fa fa-pinterest-square',
			'fa fa-plane',
			'fa fa-play-circle fa-fw',
			'fa fa-play-circle-o',
			'fa fa-plus',
			'fa fa-plus-circle',
			'fa fa-plus-square',
			'fa fa-plus-square-o',
			'fa fa-power-off',
			'fa fa-print',
			'fa fa-puzzle-piece',
			'fa fa-qq',
			'fa fa-qrcode',
			'fa fa-question',
			'fa fa-question-circle',
			'fa fa-quote-left',
			'fa fa-quote-right',
			'fa fa-ra',
			'fa fa-random',
			'fa fa-rebel',
			'fa fa-recycle',
			'fa fa-reddit',
			'fa fa-reddit-square',
			'fa fa-refresh',
			'fa fa-renren',
			'fa fa-reorder',
			'fa fa-repeat',
			'fa fa-reply',
			'fa fa-reply-all',
			'fa fa-retweet',
			'fa fa-rmb',
			'fa fa-road',
			'fa fa-rocket',
			'fa fa-rotate-left',
			'fa fa-rotate-right',
			'fa fa-rouble',
			'fa fa-rss',
			'fa fa-rss-square',
			'fa fa-rub',
			'fa fa-ruble',
			'fa fa-rupee',
			'fa fa-save',
			'fa fa-scissors',
			'fa fa-search',
			'fa fa-search-minus',
			'fa fa-search-plus',
			'fa fa-send',
			'fa fa-send-o',
			'fa fa-share-alt',
			'fa fa-share-alt-square',
			'fa fa-share-square',
			'fa fa-share-square-o',
			'fa fa-shield',
			'fa fa-shopping-cart',
			'fa fa-sign-in',
			'fa fa-sign-out',
			'fa fa-signal',
			'fa fa-sitemap',
			'fa fa-skype',
			'fa fa-slack',
			'fa fa-sliders',
			'fa fa-smile-o',
			'fa fa-sort',
			'fa fa-sort-alpha-asc',
			'fa fa-sort-alpha-desc',
			'fa fa-sort-amount-asc',
			'fa fa-sort-amount-desc',
			'fa fa-sort-asc',
			'fa fa-sort-desc',
			'fa fa-sort-down',
			'fa fa-sort-numeric-asc',
			'fa fa-sort-numeric-desc',
			'fa fa-sort-up',
			'fa fa-soundcloud',
			'fa fa-space-shuttle',
			'fa fa-spinner fa-fw',
			'fa fa-spoon',
			'fa fa-spotify',
			'fa fa-square',
			'fa fa-square-o',
			'fa fa-stack-exchange',
			'fa fa-stack-overflow',
			'fa fa-star',
			'fa fa-star-half',
			'fa fa-star-half-empty',
			'fa fa-star-half-full',
			'fa fa-star-half-o',
			'fa fa-star-o',
			'fa fa-steam',
			'fa fa-steam-square',
			'fa fa-step-backward',
			'fa fa-step-forward',
			'fa fa-stethoscope',
			'fa fa-stop',
			'fa fa-strikethrough',
			'fa fa-stumbleupon',
			'fa fa-stumbleupon-circle',
			'fa fa-subscript',
			'fa fa-suitcase',
			'fa fa-sun-o',
			'fa fa-superscript',
			'fa fa-support',
			'fa fa-tablet',
			'fa fa-tachometer',
			'fa fa-tag',
			'fa fa-tags',
			'fa fa-tasks',
			'fa fa-taxi',
			'fa fa-tencent-weibo',
			'fa fa-terminal',
			'fa fa-text-height',
			'fa fa-text-width',
			'fa fa-th-large',
			'fa fa-th-list',
			'fa fa-thumb-tack',
			'fa fa-thumbs-down',
			'fa fa-thumbs-o-down',
			'fa fa-thumbs-o-up',
			'fa fa-thumbs-up',
			'fa fa-ticket',
			'fa fa-times',
			'fa fa-times-circle',
			'fa fa-times-circle-o',
			'fa fa-tint',
			'fa fa-toggle-down',
			'fa fa-toggle-left',
			'fa fa-toggle-right',
			'fa fa-toggle-up',
			'fa fa-trash-o',
			'fa fa-tree',
			'fa fa-trello',
			'fa fa-trophy',
			'fa fa-truck',
			'fa fa-try',
			'fa fa-tumblr',
			'fa fa-tumblr-square',
			'fa fa-turkish-lira',
			'fa fa-twitter',
			'fa fa-twitter-square',
			'fa fa-umbrella',
			'fa fa-underline',
			'fa fa-undo',
			'fa fa-university',
			'fa fa-unlink',
			'fa fa-unlock',
			'fa fa-unlock-alt',
			'fa fa-unsorted',
			'fa fa-upload',
			'fa fa-usd',
			'fa fa-user',
			'fa fa-user-md',
			'fa fa-users',
			'fa fa-video-camera',
			'fa fa-vimeo-square',
			'fa fa-vine',
			'fa fa-vk',
			'fa fa-volume-down',
			'fa fa-volume-off',
			'fa fa-volume-up',
			'fa fa-warning',
			'fa fa-wechat',
			'fa fa-weibo',
			'fa fa-weixin',
			'fa fa-wheelchair',
			'fa fa-windows',
			'fa fa-won fa-fw',
			'fa fa-wordpress',
			'fa fa-wrench',
			'fa fa-xing',
			'fa fa-xing-square',
			'fa fa-yahoo',
			'fa fa-yen',
			'fa fa-youtube-play',
			'fa fa-youtube-square',
		);

		$this->elicons = array(
			'icon arrow_up',
			'icon arrow_down',
			'icon arrow_left',
			'icon arrow_right',
			'icon arrow_left-up',
			'icon arrow_right-up',
			'icon arrow_right-down',
			'icon arrow_left-down',
			'icon arrow-up-down',
			'icon arrow_up-down_alt',
			'icon arrow_left-right_alt',
			'icon arrow_left-right',
			'icon arrow_expand_alt2',
			'icon arrow_expand_alt',
			'icon arrow_condense',
			'icon arrow_expand',
			'icon arrow_move',
			'icon arrow_carrot-up',
			'icon arrow_carrot-down',
			'icon arrow_carrot-left',
			'icon arrow_carrot-right',
			'icon arrow_carrot-2up',
			'icon arrow_carrot-2down',
			'icon arrow_carrot-2left',
			'icon arrow_carrot-2right',
			'icon arrow_carrot-up_alt2',
			'icon arrow_carrot-down_alt2',
			'icon arrow_carrot-left_alt2',
			'icon arrow_carrot-right_alt2',
			'icon arrow_carrot-2up_alt2',
			'icon arrow_carrot-2down_alt2',
			'icon arrow_carrot-2left_alt2',
			'icon arrow_carrot-2right_alt2',
			'icon arrow_triangle-up',
			'icon arrow_triangle-down',
			'icon arrow_triangle-left',
			'icon arrow_triangle-right',
			'icon arrow_triangle-up_alt2',
			'icon arrow_triangle-down_alt2',
			'icon arrow_triangle-left_alt2',
			'icon arrow_triangle-right_alt2',
			'icon arrow_back',
			'icon icon_minus-06',
			'icon icon_plus',
			'icon icon_close',
			'icon icon_check',
			'icon icon_minus_alt2',
			'icon icon_plus_alt2',
			'icon icon_close_alt2',
			'icon icon_check_alt2',
			'icon icon_zoom-out_alt',
			'icon icon_zoom-in_alt',
			'icon icon_search',
			'icon icon_box-empty',
			'icon icon_box-selected',
			'icon icon_minus-box',
			'icon icon_plus-box',
			'icon icon_box-checked',
			'icon icon_circle-empty',
			'icon icon_circle-slelected',
			'icon icon_stop_alt2',
			'icon icon_stop',
			'icon icon_pause_alt2',
			'icon icon_pause',
			'icon icon_menu',
			'icon icon_menu-square_alt2',
			'icon icon_menu-circle_alt2',
			'icon icon_ul',
			'icon icon_ol',
			'icon icon_adjust-horiz',
			'icon icon_adjust-vert',
			'icon icon_document_alt',
			'icon icon_documents_alt',
			'icon icon_pencil',
			'icon icon_pencil-edit_alt',
			'icon icon_pencil-edit',
			'icon icon_folder-alt',
			'icon icon_folder-open_alt',
			'icon icon_folder-add_alt',
			'icon icon_info_alt',
			'icon icon_error-oct_alt',
			'icon icon_error-circle_alt',
			'icon icon_error-triangle_alt',
			'icon icon_question_alt2',
			'icon icon_question',
			'icon icon_comment_alt',
			'icon icon_chat_alt',
			'icon icon_vol-mute_alt',
			'icon icon_volume-low_alt',
			'icon icon_volume-high_alt',
			'icon icon_quotations',
			'icon icon_quotations_alt2',
			'icon icon_clock_alt',
			'icon icon_lock_alt',
			'icon icon_lock-open_alt',
			'icon icon_key_alt',
			'icon icon_cloud_alt',
			'icon icon_cloud-upload_alt',
			'icon icon_cloud-download_alt',
			'icon icon_image',
			'icon icon_images',
			'icon icon_lightbulb_alt',
			'icon icon_gift_alt',
			'icon icon_house_alt',
			'icon icon_genius',
			'icon icon_mobile',
			'icon icon_tablet',
			'icon icon_laptop',
			'icon icon_desktop',
			'icon icon_camera_alt',
			'icon icon_mail_alt',
			'icon icon_cone_alt',
			'icon icon_ribbon_alt',
			'icon icon_bag_alt',
			'icon icon_creditcard',
			'icon icon_cart_alt',
			'icon icon_paperclip',
			'icon icon_tag_alt',
			'icon icon_tags_alt',
			'icon icon_trash_alt',
			'icon icon_cursor_alt',
			'icon icon_mic_alt',
			'icon icon_compass_alt',
			'icon icon_pin_alt',
			'icon icon_pushpin_alt',
			'icon icon_map_alt',
			'icon icon_drawer_alt',
			'icon icon_toolbox_alt',
			'icon icon_book_alt',
			'icon icon_calendar',
			'icon icon_film',
			'icon icon_table',
			'icon icon_contacts_alt',
			'icon icon_headphones',
			'icon icon_lifesaver',
			'icon icon_piechart',
			'icon icon_refresh',
			'icon icon_link_alt',
			'icon icon_link',
			'icon icon_loading',
			'icon icon_blocked',
			'icon icon_archive_alt',
			'icon icon_heart_alt',
			'icon icon_printer',
			'icon icon_calulator',
			'icon icon_building',
			'icon icon_floppy',
			'icon icon_drive',
			'icon icon_search-2',
			'icon icon_id',
			'icon icon_id-2',
			'icon icon_puzzle',
			'icon icon_like',
			'icon icon_dislike',
			'icon icon_mug',
			'icon icon_currency',
			'icon icon_wallet',
			'icon icon_pens',
			'icon icon_easel',
			'icon icon_flowchart',
			'icon icon_datareport',
			'icon icon_briefcase',
			'icon icon_shield',
			'icon icon_percent',
			'icon icon_globe',
			'icon icon_globe-2',
			'icon icon_target',
			'icon icon_hourglass',
			'icon icon_balance',
			'icon icon_star_alt',
			'icon icon_star-half_alt',
			'icon icon_star',
			'icon icon_star-half',
			'icon icon_tools',
			'icon icon_tool',
			'icon icon_cog',
			'icon icon_cogs',
			'icon arrow_up_alt',
			'icon arrow_down_alt',
			'icon arrow_left_alt',
			'icon arrow_right_alt',
			'icon arrow_left-up_alt',
			'icon arrow_right-up_alt',
			'icon arrow_right-down_alt',
			'icon arrow_left-down_alt',
			'icon arrow_condense_alt',
			'icon arrow_expand_alt3',
			'icon arrow_carrot_up_alt',
			'icon arrow_carrot-down_alt',
			'icon arrow_carrot-left_alt',
			'icon arrow_carrot-right_alt',
			'icon arrow_carrot-2up_alt',
			'icon arrow_carrot-2dwnn_alt',
			'icon arrow_carrot-2left_alt',
			'icon arrow_carrot-2right_alt',
			'icon arrow_triangle-up_alt',
			'icon arrow_triangle-down_alt',
			'icon arrow_triangle-left_alt',
			'icon arrow_triangle-right_alt',
			'icon icon_minus_alt',
			'icon icon_plus_alt',
			'icon icon_close_alt',
			'icon icon_check_alt',
			'icon icon_zoom-out',
			'icon icon_zoom-in',
			'icon icon_stop_alt',
			'icon icon_menu-square_alt',
			'icon icon_menu-circle_alt',
			'icon icon_document',
			'icon icon_documents',
			'icon icon_pencil_alt',
			'icon icon_folder',
			'icon icon_folder-open',
			'icon icon_folder-add',
			'icon icon_folder_upload',
			'icon icon_folder_download',
			'icon icon_info',
			'icon icon_error-circle',
			'icon icon_error-oct',
			'icon icon_error-triangle',
			'icon icon_question_alt',
			'icon icon_comment',
			'icon icon_chat',
			'icon icon_vol-mute',
			'icon icon_volume-low',
			'icon icon_volume-high',
			'icon icon_quotations_alt',
			'icon icon_clock',
			'icon icon_lock',
			'icon icon_lock-open',
			'icon icon_key',
			'icon icon_cloud',
			'icon icon_cloud-upload',
			'icon icon_cloud-download',
			'icon icon_lightbulb',
			'icon icon_gift',
			'icon icon_house',
			'icon icon_camera',
			'icon icon_mail',
			'icon icon_cone',
			'icon icon_ribbon',
			'icon icon_bag',
			'icon icon_cart',
			'icon icon_tag',
			'icon icon_tags',
			'icon icon_trash',
			'icon icon_cursor',
			'icon icon_mic',
			'icon icon_compass',
			'icon icon_pin',
			'icon icon_pushpin',
			'icon icon_map',
			'icon icon_drawer',
			'icon icon_toolbox',
			'icon icon_book',
			'icon icon_contacts',
			'icon icon_archive',
			'icon icon_heart',
			'icon icon_profile',
			'icon icon_group',
			'icon icon_grid-2x2',
			'icon icon_grid-3x3',
			'icon icon_music',
			'icon icon_pause_alt',
			'icon icon_phone',
			'icon icon_upload',
			'icon icon_download',
			'icon icon_rook',
			'icon icon_printer-alt',
			'icon icon_calculator_alt',
			'icon icon_building_alt',
			'icon icon_floppy_alt',
			'icon icon_drive_alt',
			'icon icon_search_alt',
			'icon icon_id_alt',
			'icon icon_id-2_alt',
			'icon icon_puzzle_alt',
			'icon icon_like_alt',
			'icon icon_dislike_alt',
			'icon icon_mug_alt',
			'icon icon_currency_alt',
			'icon icon_wallet_alt',
			'icon icon_pens_alt',
			'icon icon_easel_alt',
			'icon icon_flowchart_alt',
			'icon icon_datareport_alt',
			'icon icon_briefcase_alt',
			'icon icon_shield_alt',
			'icon icon_percent_alt',
			'icon icon_globe_alt',
			'icon icon_clipboard',
			'icon social_facebook',
			'icon social_twitter',
			'icon social_pinterest',
			'icon social_googleplus',
			'icon social_tumblr',
			'icon social_tumbleupon',
			'icon social_wordpress',
			'icon social_instagram',
			'icon social_dribbble',
			'icon social_vimeo',
			'icon social_linkedin',
			'icon social_rss',
			'icon social_deviantart',
			'icon social_share',
			'icon social_myspace',
			'icon social_skype',
			'icon social_youtube',
			'icon social_picassa',
			'icon social_googledrive',
			'icon social_flickr',
			'icon social_blogger',
			'icon social_spotify',
			'icon social_delicious',
			'icon social_facebook_circle',
			'icon social_twitter_circle',
			'icon social_pinterest_circle',
			'icon social_googleplus_circle',
			'icon social_tumblr_circle',
			'icon social_stumbleupon_circle',
			'icon social_wordpress_circle',
			'icon social_instagram_circle',
			'icon social_dribbble_circle',
			'icon social_vimeo_circle',
			'icon social_linkedin_circle',
			'icon social_rss_circle',
			'icon social_deviantart_circle',
			'icon social_share_circle',
			'icon social_myspace_circle',
			'icon social_skype_circle',
			'icon social_youtube_circle',
			'icon social_picassa_circle',
			'icon social_googledrive_alt2',
			'icon social_flickr_circle',
			'icon social_blogger_circle',
			'icon social_spotify_circle',
			'icon social_delicious_circle',
			'icon social_facebook_square',
			'icon social_twitter_square',
			'icon social_pinterest_square',
			'icon social_googleplus_square',
			'icon social_tumblr_square',
			'icon social_stumbleupon_square',
			'icon social_wordpress_square',
			'icon social_instagram_square',
			'icon social_dribbble_square',
			'icon social_vimeo_square',
			'icon social_linkedin_square',
			'icon social_rss_square',
			'icon social_deviantart_square',
			'icon social_share_square',
			'icon social_myspace_square',
			'icon social_skype_square',
			'icon social_youtube_square',
			'icon social_picassa_square',
			'icon social_googledrive_square',
			'icon social_flickr_square',
			'icon social_blogger_square',
			'icon social_spotify_square',
			'icon social_delicious_square',
		);

		$this->outlinediconset = array(
			'icon icon-boat',
			'icon icon-booknote',
			'icon icon-booknote-add',
			'icon icon-booknote-remove',
			'icon icon-camera-1',
			'icon icon-camera-2',
			'icon icon-cloud-check',
			'icon icon-cloud-delete',
			'icon icon-cloud-download',
			'icon icon-cloud-upload',
			'icon icon-cloudy',
			'icon icon-cocktail',
			'icon icon-coffee',
			'icon icon-compass',
			'icon icon-compress',
			'icon icon-cutlery',
			'icon icon-delete',
			'icon icon-delete-folder',
			'icon icon-dialogue-add',
			'icon icon-dialogue-delete',
			'icon icon-dialogue-happy',
			'icon icon-dialogue-sad',
			'icon icon-dialogue-text',
			'icon icon-dialogue-think',
			'icon icon-diamond',
			'icon icon-dish-fork',
			'icon icon-dish-spoon',
			'icon icon-download',
			'icon icon-download-folder',
			'icon icon-expand',
			'icon icon-eye',
			'icon icon-fast-food',
			'icon icon-flag',
			'icon icon-folder',
			'icon icon-geolocalizator',
			'icon icon-globe',
			'icon icon-graph',
			'icon icon-graph-descending',
			'icon icon-graph-rising',
			'icon icon-hammer',
			'icon icon-happy-drop',
			'icon icon-headphones',
			'icon icon-heart',
			'icon icon-heart-broken',
			'icon icon-home',
			'icon icon-hourglass',
			'icon icon-image',
			'icon icon-key',
			'icon icon-life-buoy',
			'icon icon-list',
			'icon icon-lock-closed',
			'icon icon-lock-open',
			'icon icon-loudspeaker',
			'icon icon-magnifier',
			'icon icon-magnifier-minus',
			'icon icon-magnifier-plus',
			'icon icon-mail',
			'icon icon-mail-open',
			'icon icon-map',
			'icon icon-medical-case',
			'icon icon-microphone-1',
			'icon icon-microphone-2',
			'icon icon-minus',
			'icon icon-multiple-image',
			'icon icon-music-back',
			'icon icon-music-backtoend',
			'icon icon-music-eject',
			'icon icon-music-forward',
			'icon icon-music-forwardtoend',
			'icon icon-music-pause',
			'icon icon-music-play',
			'icon icon-music-random',
			'icon icon-music-repeat',
			'icon icon-music-stop',
			'icon icon-musical-note',
			'icon icon-musical-note-2',
			'icon icon-old-video-cam',
			'icon icon-paper-pen',
			'icon icon-paper-pencil',
			'icon icon-paper-sheet',
			'icon icon-pen-pencil-ruler',
			'icon icon-pencil',
			'icon icon-pencil-ruler',
			'icon icon-plus',
			'icon icon-portable-pc',
			'icon icon-pricetag',
			'icon icon-printer',
			'icon icon-profile',
			'icon icon-profile-add',
			'icon icon-profile-remove',
			'icon icon-rainy',
			'icon icon-rotate',
			'icon icon-setting-1',
			'icon icon-setting-2',
			'icon icon-share',
			'icon icon-shield-down',
			'icon icon-shield-left',
			'icon icon-shield-right',
			'icon icon-shield-up',
			'icon icon-shopping-cart',
			'icon icon-shopping-cart-content',
			'icon icon-sinth',
			'icon icon-smartphone',
			'icon icon-spread',
			'icon icon-squares',
			'icon icon-stormy',
			'icon icon-sunny',
			'icon icon-tablet',
			'icon icon-three-stripes-horiz',
			'icon icon-three-stripes-vert',
			'icon icon-ticket',
			'icon icon-todolist',
			'icon icon-todolist-add',
			'icon icon-todolist-check',
			'icon icon-trash-bin',
			'icon icon-tshirt',
			'icon icon-tv-monitor',
			'icon icon-umbrella',
			'icon icon-upload',
			'icon icon-upload-folder',
			'icon icon-variable',
			'icon icon-video-cam',
			'icon icon-volume-higher',
			'icon icon-volume-lower',
			'icon icon-volume-off',
			'icon icon-watch',
			'icon icon-waterfall',
			'icon icon-website-1',
			'icon icon-website-2',
			'icon icon-wine',
			'icon icon-calendar',
			'icon icon-alarm-clock',
			'icon icon-add-folder',
			'icon icon-accelerator',
			'icon icon-agenda',
			'icon icon-arrow-left',
			'icon icon-arrow-down',
			'icon icon-battery-1',
			'icon icon-case',
			'icon icon-arrow-up',
			'icon icon-arrow-right',
			'icon icon-case-2',
			'icon icon-cd',
			'icon icon-battery-2',
			'icon icon-battery-3',
			'icon icon-check',
			'icon icon-battery-4',
			'icon icon-chronometer',
			'icon icon-clock',
			'icon icon-blackboard-graph',
		);

		$this->ionicons = array(
			'ion-ionic',
			'ion-arrow-up-a',
			'ion-arrow-right-a',
			'ion-arrow-down-a',
			'ion-arrow-left-a',
			'ion-arrow-up-b',
			'ion-arrow-right-b',
			'ion-arrow-down-b',
			'ion-arrow-left-b',
			'ion-arrow-up-c',
			'ion-arrow-right-c',
			'ion-arrow-down-c',
			'ion-arrow-left-c',
			'ion-arrow-return-right',
			'ion-arrow-return-left',
			'ion-arrow-swap',
			'ion-arrow-shrink',
			'ion-arrow-expand',
			'ion-arrow-move',
			'ion-arrow-resize',
			'ion-chevron-up',
			'ion-chevron-right',
			'ion-chevron-down',
			'ion-chevron-left',
			'ion-navicon-round',
			'ion-navicon',
			'ion-drag',
			'ion-log-in',
			'ion-log-out',
			'ion-checkmark-round',
			'ion-checkmark',
			'ion-checkmark-circled',
			'ion-close-round',
			'ion-close',
			'ion-close-circled',
			'ion-plus-round',
			'ion-plus',
			'ion-plus-circled',
			'ion-minus-round',
			'ion-minus',
			'ion-minus-circled',
			'ion-information',
			'ion-information-circled',
			'ion-help',
			'ion-help-circled',
			'ion-help-buoy',
			'ion-alert',
			'ion-alert-circled',
			'ion-refresh',
			'ion-refreshing',
			'ion-loop',
			'ion-looping',
			'ion-shuffle',
			'ion-home',
			'ion-search',
			'ion-flag',
			'ion-star',
			'ion-heart',
			'ion-gear-a',
			'ion-gear-b',
			'ion-settings',
			'ion-wrench',
			'ion-hammer',
			'ion-edit',
			'ion-trash-a',
			'ion-trash-b',
			'ion-document',
			'ion-document-text',
			'ion-clipboard',
			'ion-bookmark',
			'ion-email',
			'ion-folder',
			'ion-filing',
			'ion-archive',
			'ion-reply',
			'ion-reply-all',
			'ion-forward',
			'ion-share',
			'ion-paper-airplane',
			'ion-link',
			'ion-paperclip',
			'ion-compose',
			'ion-briefcase',
			'ion-medkit',
			'ion-at',
			'ion-pound',
			'ion-cloud',
			'ion-upload',
			'ion-more',
			'ion-grid',
			'ion-calendar',
			'ion-clock',
			'ion-compass',
			'ion-pinpoint',
			'ion-pin',
			'ion-navigate',
			'ion-location',
			'ion-map',
			'ion-model-s',
			'ion-locked',
			'ion-unlocked',
			'ion-key',
			'ion-arrow-graph-up-right',
			'ion-arrow-graph-down-right',
			'ion-arrow-graph-up-left',
			'ion-arrow-graph-down-left',
			'ion-stats-bars',
			'ion-connection-bars',
			'ion-pie-graph',
			'ion-chatbubble',
			'ion-chatbubble-working',
			'ion-chatbubbles',
			'ion-chatbox',
			'ion-chatbox-working',
			'ion-chatboxes',
			'ion-person',
			'ion-person-add',
			'ion-person-stalker',
			'ion-woman',
			'ion-man',
			'ion-female',
			'ion-male',
			'ion-fork',
			'ion-knife',
			'ion-spoon',
			'ion-beer',
			'ion-wineglass',
			'ion-coffee',
			'ion-icecream',
			'ion-pizza',
			'ion-power',
			'ion-battery-full',
			'ion-battery-half',
			'ion-battery-low',
			'ion-battery-empty',
			'ion-battery-charging',
			'ion-wifi',
			'ion-bluetooth',
			'ion-calculator',
			'ion-camera',
			'ion-eye',
			'ion-eye-disabled',
			'ion-flash',
			'ion-flash-off',
			'ion-image',
			'ion-images',
			'ion-contrast',
			'ion-monitor',
			'ion-laptop',
			'ion-ipad',
			'ion-iphone',
			'ion-ipod',
			'ion-printer',
			'ion-usb',
			'ion-bug',
			'ion-code',
			'ion-code-working',
			'ion-code-download',
			'ion-fork-repo',
			'ion-game-controller-a',
			'ion-game-controller-b',
			'ion-xbox',
			'ion-playstation',
			'ion-videocamera',
			'ion-film-marker',
			'ion-disc',
			'ion-headphone',
			'ion-music-note',
			'ion-radio-waves',
			'ion-speakerphone',
			'ion-mic-a',
			'ion-mic-b',
			'ion-mic-c',
			'ion-volume-high',
			'ion-volume-medium',
			'ion-volume-low',
			'ion-volume-mute',
			'ion-levels',
			'ion-play',
			'ion-pause',
			'ion-stop',
			'ion-record',
			'ion-skip-forward',
			'ion-skip-backward',
			'ion-eject',
			'ion-bag',
			'ion-card',
			'ion-pricetag',
			'ion-pricetags',
			'ion-thumbsup',
			'ion-thumbsdown',
			'ion-magnet',
			'ion-beaker',
			'ion-flask',
			'ion-egg',
			'ion-earth',
			'ion-lightbulb',
			'ion-leaf',
			'ion-waterdrop',
			'ion-umbrella',
			'ion-nuclear',
			'ion-no-smoking',
			'ion-thermometer',
			'ion-speedometer',
			'ion-plane',
			'ion-jet',
			'ion-load-a',
			'ion-loading-a',
			'ion-load-b',
			'ion-loading-b',
			'ion-load-c',
			'ion-loading-c',
			'ion-load-d',
			'ion-loading-d',
			'ion-ios7-ionic-outline',
			'ion-ios7-arrow-back',
			'ion-ios7-arrow-forward',
			'ion-ios7-arrow-up',
			'ion-ios7-arrow-right',
			'ion-ios7-arrow-down',
			'ion-ios7-arrow-left',
			'ion-ios7-arrow-thin-up',
			'ion-ios7-arrow-thin-right',
			'ion-ios7-arrow-thin-down',
			'ion-ios7-arrow-thin-left',
			'ion-ios7-circle-filled',
			'ion-ios7-circle-outline',
			'ion-ios7-checkmark-empty',
			'ion-ios7-checkmark-outline',
			'ion-ios7-checkmark',
			'ion-ios7-plus-empty',
			'ion-ios7-plus-outline',
			'ion-ios7-plus',
			'ion-ios7-close-empty',
			'ion-ios7-close-outline',
			'ion-ios7-close',
			'ion-ios7-minus-empty',
			'ion-ios7-minus-outline',
			'ion-ios7-minus',
			'ion-ios7-information-empty',
			'ion-ios7-information-outline',
			'ion-ios7-information',
			'ion-ios7-help-empty',
			'ion-ios7-help-outline',
			'ion-ios7-help',
			'ion-ios7-search',
			'ion-ios7-search-strong',
			'ion-ios7-star',
			'ion-ios7-star-outline',
			'ion-ios7-heart',
			'ion-ios7-heart-outline',
			'ion-ios7-more',
			'ion-ios7-more-outline',
			'ion-ios7-cloud',
			'ion-ios7-cloud-outline',
			'ion-ios7-cloud-upload',
			'ion-ios7-cloud-upload-outline',
			'ion-ios7-cloud-download',
			'ion-ios7-cloud-download-outline',
			'ion-ios7-upload',
			'ion-ios7-upload-outline',
			'ion-ios7-download',
			'ion-ios7-download-outline',
			'ion-ios7-refresh-outline',
			'ion-ios7-refresh',
			'ion-ios7-refresh-empty',
			'ion-ios7-reload',
			'ion-ios7-reloading',
			'ion-ios7-bookmarks',
			'ion-ios7-bookmarks-outline',
			'ion-ios7-flag',
			'ion-ios7-flag-outline',
			'ion-ios7-glasses',
			'ion-ios7-glasses-outline',
			'ion-ios7-browsers',
			'ion-ios7-browsers-outline',
			'ion-ios7-at',
			'ion-ios7-at-outline',
			'ion-ios7-cart',
			'ion-ios7-cart-outline',
			'ion-ios7-pricetag',
			'ion-ios7-pricetag-outline',
			'ion-ios7-chatboxes-outline',
			'ion-ios7-chatbubble',
			'ion-ios7-chatbubble-outline',
			'ion-ios7-cog',
			'ion-ios7-cog-outline',
			'ion-ios7-gear',
			'ion-ios7-gear-outline',
			'ion-ios7-pie',
			'ion-ios7-pie-outline',
			'ion-ios7-filing',
			'ion-ios7-filing-outline',
			'ion-ios7-box',
			'ion-ios7-box-outline',
			'ion-ios7-compose',
			'ion-ios7-compose-outline',
			'ion-ios7-trash',
			'ion-ios7-trash-outline',
			'ion-ios7-copy',
			'ion-ios7-copy-outline',
			'ion-ios7-email',
			'ion-ios7-email-outline',
			'ion-ios7-undo',
			'ion-ios7-undo-outline',
			'ion-ios7-redo',
			'ion-ios7-redo-outline',
			'ion-ios7-paperplane',
			'ion-ios7-paperplane-outline',
			'ion-ios7-folder',
			'ion-ios7-folder-outline',
			'ion-ios7-world',
			'ion-ios7-world-outline',
			'ion-ios7-alarm',
			'ion-ios7-alarm-outline',
			'ion-ios7-speedometer',
			'ion-ios7-speedometer-outline',
			'ion-ios7-stopwatch',
			'ion-ios7-stopwatch-outline',
			'ion-ios7-timer',
			'ion-ios7-timer-outline',
			'ion-ios7-clock',
			'ion-ios7-clock-outline',
			'ion-ios7-time',
			'ion-ios7-time-outline',
			'ion-ios7-calendar',
			'ion-ios7-calendar-outline',
			'ion-ios7-photos',
			'ion-ios7-photos-outline',
			'ion-ios7-albums',
			'ion-ios7-albums-outline',
			'ion-ios7-camera',
			'ion-ios7-camera-outline',
			'ion-ios7-eye',
			'ion-ios7-eye-outline',
			'ion-ios7-bolt',
			'ion-ios7-bolt-outline',
			'ion-ios7-briefcase',
			'ion-ios7-briefcase-outline',
			'ion-ios7-medkit',
			'ion-ios7-medkit-outline',
			'ion-ios7-infinite',
			'ion-ios7-infinite-outline',
			'ion-ios7-calculator',
			'ion-ios7-calculator-outline',
			'ion-ios7-keypad',
			'ion-ios7-keypad-outline',
			'ion-ios7-telephone',
			'ion-ios7-telephone-outline',
			'ion-ios7-drag',
			'ion-ios7-location',
			'ion-ios7-location-outline',
			'ion-ios7-navigate',
			'ion-ios7-navigate-outline',
			'ion-ios7-locked',
			'ion-ios7-locked-outline',
			'ion-ios7-unlocked',
			'ion-ios7-unlocked-outline',
			'ion-ios7-monitor',
			'ion-ios7-monitor-outline',
			'ion-ios7-printer',
			'ion-ios7-printer-outline',
			'ion-ios7-person',
			'ion-ios7-person-outline',
			'ion-ios7-personadd',
			'ion-ios7-personadd-outline',
			'ion-ios7-people',
			'ion-ios7-people-outline',
			'ion-ios7-sunny',
			'ion-ios7-sunny-outline',
			'ion-ios7-partlysunny',
			'ion-ios7-partlysunny-outline',
			'ion-ios7-cloudy',
			'ion-ios7-cloudy-outline',
			'ion-ios7-rainy',
			'ion-ios7-rainy-outline',
			'ion-ios7-thunderstorm',
			'ion-ios7-thunderstorm-outline',
			'ion-ios7-snowy',
			'ion-ios7-moon',
			'ion-ios7-moon-outline',
			'ion-ios7-cloudy-night',
			'ion-ios7-cloudy-night-outline',
			'ion-ios7-musical-notes',
			'ion-ios7-musical-note',
			'ion-ios7-bell',
			'ion-ios7-bell-outline',
			'ion-ios7-mic',
			'ion-ios7-mic-outline',
			'ion-ios7-mic-off',
			'ion-ios7-volume-high',
			'ion-ios7-volume-low',
			'ion-ios7-play',
			'ion-ios7-play-outline',
			'ion-ios7-pause',
			'ion-ios7-pause-outline',
			'ion-ios7-recording',
			'ion-ios7-recording-outline',
			'ion-ios7-fastforward',
			'ion-ios7-fastforward-outline',
			'ion-ios7-rewind',
			'ion-ios7-rewind-outline',
			'ion-ios7-skipbackward',
			'ion-ios7-skipbackward-outline',
			'ion-ios7-skipforward',
			'ion-ios7-skipforward-outline',
			'ion-ios7-videocam',
			'ion-ios7-videocam-outline',
			'ion-ios7-film',
			'ion-ios7-film-outline',
			'ion-ios7-lightbulb',
			'ion-ios7-lightbulb-outline',
			'ion-ios7-wineglass',
			'ion-ios7-wineglass-outline',
			'ion-android-system-back',
			'ion-android-system-home',
			'ion-android-system-windows',
			'ion-android-wifi',
			'ion-android-battery',
			'ion-android-storage',
			'ion-android-keypad',
			'ion-android-call',
			'ion-android-arrow-back',
			'ion-android-arrow-up-right',
			'ion-android-arrow-down-right',
			'ion-android-arrow-down-left',
			'ion-android-arrow-up-left',
			'ion-android-sort',
			'ion-android-dropdown',
			'ion-android-settings',
			'ion-android-mixer',
			'ion-android-display',
			'ion-android-star',
			'ion-android-search',
			'ion-android-microphone',
			'ion-android-more',
			'ion-android-checkmark',
			'ion-android-information',
			'ion-android-add',
			'ion-android-remove',
			'ion-android-close',
			'ion-android-trash',
			'ion-android-volume',
			'ion-android-printer',
			'ion-android-download',
			'ion-android-hand',
			'ion-android-developer',
			'ion-android-calendar',
			'ion-android-clock',
			'ion-android-alarm',
			'ion-android-stopwatch',
			'ion-android-data',
			'ion-android-timer',
			'ion-android-camera',
			'ion-android-image',
			'ion-android-location',
			'ion-android-locate',
			'ion-android-earth',
			'ion-android-book',
			'ion-android-note',
			'ion-android-promotion',
			'ion-android-playstore',
			'ion-android-share',
			'ion-android-send',
			'ion-android-mail',
			'ion-android-inbox',
			'ion-android-archive',
			'ion-android-folder',
			'ion-android-forums',
			'ion-android-chat',
			'ion-android-contact',
			'ion-android-contacts',
			'ion-android-friends',
			'ion-android-add-contact',
			'ion-android-social-user',
			'ion-android-social',
			'ion-android-reminder',
			'ion-android-lightbulb',
			'ion-social-twitter',
			'ion-social-twitter-outline',
			'ion-social-facebook',
			'ion-social-facebook-outline',
			'ion-social-googleplus',
			'ion-social-googleplus-outline',
			'ion-social-dribbble',
			'ion-social-dribbble-outline',
			'ion-social-github',
			'ion-social-github-outline',
			'ion-social-pinterest',
			'ion-social-pinterest-outline',
			'ion-social-rss',
			'ion-social-rss-outline',
			'ion-social-tumblr',
			'ion-social-tumblr-outline',
			'ion-social-wordpress',
			'ion-social-wordpress-outline',
			'ion-social-reddit',
			'ion-social-reddit-outline',
			'ion-social-hackernews',
			'ion-social-hackernews-outline',
			'ion-social-designernews',
			'ion-social-designernews-outline',
			'ion-social-yahoo',
			'ion-social-yahoo-outline',
			'ion-social-buffer',
			'ion-social-buffer-outline',
			'ion-social-skype',
			'ion-social-skype-outline',
			'ion-social-linkedin',
			'ion-social-linkedin-outline',
			'ion-social-bitcoin',
			'ion-social-bitcoin-outline',
			'ion-social-vimeo',
			'ion-social-vimeo-outline',
			'ion-social-youtube',
			'ion-social-youtube-outline',
			'ion-social-dropbox',
			'ion-social-dropbox-outline',
			'ion-social-apple',
			'ion-social-apple-outline',
			'ion-social-android',
			'ion-social-android-outline',
			'ion-social-windows',
			'ion-social-windows-outline',
			'ion-social-tux',
			'ion-social-freebsd-devil',
		);

	}
	
}

?>